enum EventType {
    // For now, events sent by the server will be prefixed to ON_
    // Events sent by the client will be prefixed as nothing

    AUTHENTICATE = "AUTHENTICATE",

    ROOM_CREATE = "ROOM_CREATE",
    ROOM_JOIN = "ROOM_JOIN",
    ROOM_LEAVE = "ROOM_LEAVE",
    ROOM_UPDATE_CONFIG = "ROOM_UPDATE_CONFIG",
    ROOM_ADD_BOT = "ROOM_ADD_BOT",
    ROOM_SET_READY = "ROOM_SET_READY",
    ROOM_START = "ROOM_START",
    ROOM_REMOVE_PLAYER = "ROOM_REMOVE_PLAYER",
    ON_ROOM_STATE_UPDATE = "ON_ROOM_STATE_UPDATE",

    ON_GAME_START = "ON_GAME_START",

    REQUEST_GAME_SYNC = "REQUEST_GAME_SYNC",
    ON_GAME_SYNC = "ON_GAME_SYNC",

    DECIDE_READY = "DECIDE_READY",
    ON_GUK_START = "ON_GUK_START",

    ON_PLAYER_DREW = "ON_PLAYER_DREW",

    ON_WAITING_DECIDE = "ON_WAITING_DECIDE",
    DECIDE_DISCARD = "DECIDE_DISCARD",
    DECIDE_MERGE = "DECIDE_MERGE",
    DECIDE_RICHI = "DECIDE_RICHI",

    ON_PLAYER_DISCARD = "ON_PLAYER_DISCARD",
    ON_PLAYER_MERGE = "ON_PLAYER_MERGE",
    ON_PLAYER_RICHI = "ON_PLAYER_RICHI",
    ON_GUK_END = "ON_GUK_END", // Player SIK

    ON_GAME_END = "ON_GAME_END"
}

export default EventType;
